@startuml
title Open CVN - CVN Professional Experience Reference - ProfessionalSituation

skinparam classAttributeIconSize 0
skinparam linetype ortho
top to bottom direction
hide empty members

package "CVN Professional Experience Reference - ProfessionalSituation" as area_professional_experience_010_010_000_000_reference {
class "ProfessionalSituation" as entity_professional_experience_professionalsituation_010_010_000_000 <<entity>> {
  ambito_actividad_de_direccion_y_o_gestion : controlled_reference <<required, single>> [CVN: 010.010.000.290]
  ambito_de_la_actividad_de_direccion_y_o_gestion_otros : text <<optional, single>> [CVN: 010.010.000.300]
  categoria_profesional_puesto_o_cargo : text <<required, single>> [CVN: 010.010.000.170]
  ciudad_entidad_empleadora : text <<optional, single>> [CVN: 010.010.000.100]
  codigo_unesco_especializacion_primaria : controlled_reference <<optional, repeated>> [CVN: 010.010.000.220]
  codigo_unesco_especializacion_secundaria : controlled_reference <<optional, repeated>> [CVN: 010.010.000.230]
  codigo_unesco_especializacion_terciaria : controlled_reference <<optional, repeated>> [CVN: 010.010.000.240]
  comunidad_autonoma_region_entidad_empleadora : controlled_reference <<optional, single>> [CVN: 010.010.000.120]
  correo_electronico : text <<optional, repeated>> [CVN: 010.010.000.160]
  departamento_servicio_seccion_unidad_etc : value_object<EntityNameType> <<optional, single>> [CVN: 010.010.000.080]
  direccion_y_gestion : boolean <<optional, single>> [CVN: 010.010.000.010]
  entidad_empleadora : value_object<EntityNameType> <<required, single>> [CVN: 010.010.000.020]
  facultad_escuela_unidad_centro_hospital_o_instituto : value_object<EntityNameType> <<optional, single>> [CVN: 010.010.000.060]
  fax : text <<optional, single>> [CVN: 010.010.000.150]
  fecha_de_inicio : value_object<FlexibleDatesType> <<required, single>> [CVN: 010.010.000.180]
  funciones_desempenadas : text <<required, single>> [CVN: 010.010.000.250]
  interes_para_la_docencia_y_o_investigacion : text <<optional, single>> [CVN: 010.010.000.280]
  modalidad_de_contrato : controlled_reference <<required, single>> [CVN: 010.010.000.190]
  modalidad_de_contrato_otros : text <<optional, single>> [CVN: 010.010.000.200]
  pais_entidad_empleadora : controlled_reference <<optional, single>> [CVN: 010.010.000.110]
  palabras_clave : controlled_reference <<optional, repeated>> [CVN: 010.010.000.260]
  regimen_de_dedicacion : controlled_reference <<required, single>> [CVN: 010.010.000.210]
  situacion_profesional_actual : text <<optional, repeated>> [CVN: 010.010.000.000]
  telefono_fijo : text <<optional, single>> [CVN: 010.010.000.140]
  tipo_de_entidad : value_object<EntityTypeType> <<optional, single>> [CVN: 010.010.000.040]
  tipo_de_entidad_otros : text <<optional, single>> [CVN: 010.010.000.050]
}
note right of entity_professional_experience_professionalsituation_010_010_000_000
controlled references:
- CVN_DEDICATION_A (enumeration, enum=eligible, items=2)
- CVN_ENTITY_TYPE (code_list, enum=ineligible, items=17)
- CVN_MANAGEMENT_TYPE_A (code_list, enum=review_required, items=5)
- CVN_REGION (hierarchical_code_list, enum=ineligible, items=280)
- CVN_SITUATION_A (code_list, enum=review_required, items=8)
- ENTITY@Entity.xsd (registry, enum=ineligible)
- ISO_3166 (code_list, enum=ineligible, items=312)
- THESAURUS@thesaurus.xsd (thesaurus, enum=ineligible)
- UNESCO_CODES (hierarchical_code_list, enum=ineligible, items=2513)
end note

}


class "Curriculum" as entity_core_curriculum <<external>>

entity_core_curriculum "1" *-- "0..*" entity_professional_experience_professionalsituation_010_010_000_000 : professionalSituations

@enduml
