@startuml
title Open CVN - CVN Education Reference - Section 030 Part 3

skinparam classAttributeIconSize 0
skinparam linetype ortho
top to bottom direction
hide empty members

package "CVN Education Reference - Section 030 Part 3" as area_education_030_part_03_reference {
class "OtrasActividadesMeritosNoIncluidosEnLaRelacionAnterior" as entity_education_otrasactividadesmeritosnoincluidosenlarelacionanterior030100000000_030_100_000_000 <<entity>> {
  ciudad_de_realizacion_de_la_actividad : text <<optional, single>> [CVN: 030.100.000.060]
  comunidad_autonoma_region_de_realizacion_de_la_actividad : controlled_reference <<optional, single>> [CVN: 030.100.000.040]
  descripcion_de_la_actividad : text <<optional, single>> [CVN: 030.100.000.010]
  entidad_organizadora : value_object<EntityNameType> <<optional, single>> [CVN: 030.100.000.070]
  fecha_de_finalizacion_de_la_actividad : value_object<FlexibleDatesType> <<optional, single>> [CVN: 030.100.000.110]
  otras_actividades_meritos_no_incluidos_en_la_relacion_anterior : text <<optional, repeated>> [CVN: 030.100.000.000]
  pais_de_realizacion_de_la_actividad : controlled_reference <<optional, single>> [CVN: 030.100.000.030]
  palabras_clave : controlled_reference <<optional, repeated>> [CVN: 030.100.000.020]
  tipo_de_entidad : value_object<EntityTypeType> <<optional, single>> [CVN: 030.100.000.090]
  tipo_de_entidad_otros : text <<optional, single>> [CVN: 030.100.000.100]
}
note right of entity_education_otrasactividadesmeritosnoincluidosenlarelacionanterior030100000000_030_100_000_000
controlled references:
- CVN_ENTITY_TYPE (code_list, enum=ineligible, items=17)
- CVN_REGION (hierarchical_code_list, enum=ineligible, items=280)
- ENTITY@Entity.xsd (registry, enum=ineligible)
- ISO_3166 (code_list, enum=ineligible, items=312)
- THESAURUS@thesaurus.xsd (thesaurus, enum=ineligible)
end note

class "OtrosMeritosDeDocencia" as entity_education_otrosmeritosdedocencia_030_100_010_000 <<entity>> {
  otros_meritos_de_docencia_030_100_010_000 : text <<optional, single>> [CVN: 030.100.010.000]
  otros_meritos_de_docencia_030_100_010_010 : text <<optional, single>> [CVN: 030.100.010.010]
}

class "PluralidadInterdisciplinariedadYComplejidadDocente" as entity_education_pluralidadinterdisciplinariedadycomplejidaddocente_030_120_000_000 <<entity>> {
  pluralidad_interdisciplinariedad_y_complejidad_docente_030_120_000_000 : text <<optional, single>> [CVN: 030.120.000.000]
  pluralidad_interdisciplinariedad_y_complejidad_docente_030_120_000_010 : text <<optional, single>> [CVN: 030.120.000.010]
}

class "ProyectosDeInnovacionDocente" as entity_education_proyectosdeinnovaciondocente_030_080_000_000 <<entity>> {
  ambito_del_proyecto : controlled_reference <<required, single>> [CVN: 030.080.000.260]
  ambito_del_proyecto_otros : text <<optional, single>> [CVN: 030.080.000.270]
  aportacion_del_titular_al_proyecto : text <<optional, single>> [CVN: 030.080.000.070]
  ciudad_de_realizacion : text <<optional, single>> [CVN: 030.080.000.250]
  comunidad_autonoma_region_de_la_entidad_de_realizacion : controlled_reference <<optional, single>> [CVN: 030.080.000.030]
  duracion_de_la_participacion : duration_like <<optional, single>> [CVN: 030.080.000.200]
  entidad_es_participante_s : value_object<EntityNameType> <<optional, repeated>> [CVN: 030.080.000.150]
  entidad_financiadora : value_object<EntityNameType> <<optional, single>> [CVN: 030.080.000.090]
  fecha_de_finalizacion_de_la_participacion : value_object<FlexibleDatesType> <<optional, single>> [CVN: 030.080.000.210]
  fecha_de_inicio : value_object<FlexibleDatesType> <<required, single>> [CVN: 030.080.000.280]
  importe_concedido : decimal_number <<optional, single>> [CVN: 030.080.000.240]
  nombre_del_de_la_investigador_a_principal_ip : text <<optional, single>> [CVN: 030.080.000.220]
  numero_de_participantes : decimal_number <<optional, single>> [CVN: 030.080.000.230]
  pais_de_la_entidad_de_realizacion : controlled_reference <<optional, single>> [CVN: 030.080.000.020]
  proyectos_de_innovacion_docente : text <<optional, repeated>> [CVN: 030.080.000.000]
  regimen_de_dedicacion : controlled_reference <<optional, single>> [CVN: 030.080.000.080]
  tipo_de_convocatoria : controlled_reference <<optional, single>> [CVN: 030.080.000.130]
  tipo_de_convocatoria_otros : text <<optional, single>> [CVN: 030.080.000.140]
  tipo_de_duracion_de_la_relacion_laboral : controlled_reference <<optional, single>> [CVN: 030.080.000.190]
  tipo_de_entidad : value_object<EntityTypeType> <<optional, single>> [CVN: 030.080.000.110]
  tipo_de_entidad_otros : text <<optional, single>> [CVN: 030.080.000.120]
  tipo_de_entidad_participante : value_object<EntityTypeType> <<optional, repeated>> [CVN: 030.080.000.170]
  tipo_de_entidad_participante_otros : text <<optional, repeated>> [CVN: 030.080.000.180]
  tipo_de_participacion : controlled_reference <<optional, single>> [CVN: 030.080.000.050]
  tipo_de_participacion_otros : text <<optional, single>> [CVN: 030.080.000.060]
  titulo_del_proyecto : text <<optional, single>> [CVN: 030.080.000.010]
}
note right of entity_education_proyectosdeinnovaciondocente_030_080_000_000
controlled references:
- CVN_DEDICATION_A (enumeration, enum=eligible, items=2)
- CVN_DURATION_A (enumeration, enum=eligible, items=2)
- CVN_ENTITY_TYPE (code_list, enum=ineligible, items=17)
- CVN_PARTICIPATION_A (code_list, enum=ineligible, items=5)
- CVN_REGION (hierarchical_code_list, enum=ineligible, items=280)
- CVN_SCOPE_A (code_list, enum=review_required, items=5)
- CVN_SUMMONS_B (code_list, enum=review_required, items=3)
- ENTITY@Entity.xsd (registry, enum=ineligible)
- ISO_3166 (code_list, enum=ineligible, items=312)
end note

class "PublicacionISBNISSN" as entity_education_publicacionisbnissn_030_090_000_220 <<entity>> {
  autor_de_correspondencia : boolean <<optional, single>> [CVN: 030.090.000.400]
  identificador_de_publicacion_digital : text <<optional, repeated>> [CVN: 030.090.000.370]
  publicacion_comunidad_autonoma_region : controlled_reference <<optional, single>> [CVN: 030.090.000.280]
  publicacion_deposito_legal : text <<optional, single>> [CVN: 030.090.000.320]
  publicacion_direccion_electronica : text <<optional, single>> [CVN: 030.090.000.310]
  publicacion_editorial : value_object<EntityNameType> <<optional, single>> [CVN: 030.090.000.260]
  publicacion_fecha : value_object<FlexibleDatesType> <<optional, single>> [CVN: 030.090.000.300]
  publicacion_isbn_issn : text <<optional, repeated>> [CVN: 030.090.000.180]
  publicacion_nombre : text <<optional, single>> [CVN: 030.090.000.330]
  publicacion_pagina_inicial_final : text <<optional, single>> [CVN: 030.090.000.250]
  publicacion_pais : controlled_reference <<optional, single>> [CVN: 030.090.000.270]
  publicacion_tipo : controlled_reference <<optional, single>> [CVN: 030.090.000.220]
  publicacion_titulo : text <<optional, single>> [CVN: 030.090.000.230]
  publicacion_volumen : text <<optional, single>> [CVN: 030.090.000.240]
  tipo_de_identificador_de_publicacion_digital : controlled_reference <<optional, repeated>> [CVN: 030.090.000.380]
  tipo_de_identificador_de_publicacion_digital_otros : text <<optional, repeated>> [CVN: 030.090.000.390]
}
note right of entity_education_publicacionisbnissn_030_090_000_220
controlled references:
- CVN_PUBLICATION_A (subtype_backed_code_list, enum=ineligible, items=18)
- CVN_REGION (hierarchical_code_list, enum=ineligible, items=280)
- CVN_SOURCE_B (code_list, enum=ineligible, items=4)
- ISO_3166 (code_list, enum=ineligible, items=312)
end note

class "PublicacionNombre" as entity_education_publicacionnombre030070000190_030_070_000_190 <<entity>> {
  publicacion_nombre : text <<optional, single>> [CVN: 030.070.000.190]
}

}

entity_education_otrasactividadesmeritosnoincluidosenlarelacionanterior030100000000_030_100_000_000 -[hidden]down-> entity_education_otrosmeritosdedocencia_030_100_010_000
entity_education_otrosmeritosdedocencia_030_100_010_000 -[hidden]down-> entity_education_pluralidadinterdisciplinariedadycomplejidaddocente_030_120_000_000
entity_education_pluralidadinterdisciplinariedadycomplejidaddocente_030_120_000_000 -[hidden]down-> entity_education_proyectosdeinnovaciondocente_030_080_000_000
entity_education_proyectosdeinnovaciondocente_030_080_000_000 -[hidden]down-> entity_education_publicacionisbnissn_030_090_000_220
entity_education_publicacionisbnissn_030_090_000_220 -[hidden]down-> entity_education_publicacionnombre030070000190_030_070_000_190


@enduml
